[DWSB] update menu script to display error message on error cases

diff --git a/files/DWSB/copy/etc/dwsb/channel_roaming b/files/DWSB/copy/etc/dwsb/channel_roaming
--- a/files/DWSB/copy/etc/dwsb/channel_roaming
+++ b/files/DWSB/copy/etc/dwsb/channel_roaming
@@ -282,38 +282,47 @@ while : ; do
 		;;
 
 	9_TestRoaming)
-		inputvar="N"
-		textinput \
-			"Channel Roaming $cStaIndexStr Station TEST... Now?? [Yes/No]\n\n"$(
-			)"Please Enter:\n"$(
-			)" [Y]=Run Roaming/[N]=Exit\n" \
-			"$inputvar"
-		retval=$?
-		# Check return error
-		[ $retval -ne 0 ] && break
-		[ "$inputvar" = "Y" ] && {
-			clear
-			echo ; echo "[$aHostname]... Roaming New Frequency Now!!"
-			touch /tmp/.force_Ch_Roaming_$cStaIndex
-			sleep 1 # sleep 1 second
-
-			local TestRoamingTimer=0
-			local TestRoamingTimeout=30 # 30secs
-			while [ -e /tmp/.force_Ch_Roaming_$cStaIndex ] ; do
+		local ACT_USE_CHANNELROAM_MODE=$(grep "_USE_CHANNELROAM_MODE" $CONFIG_org | sed 's/.*="\(.*\)"/\1/')
+		if [ "$ACT_USE_CHANNELROAM_MODE" != "Y" ]; then
+			infobox \
+				 "\Z1ERROR!\n"$(
+				)"\Z0 Channel Roaming is not yet committed.\n"$(
+				)" Please try again after COMMIT it." \
+				5
+		else
+			inputvar="N"
+			textinput \
+				"Channel Roaming $cStaIndexStr Station TEST... Now?? [Yes/No]\n\n"$(
+				)"Please Enter:\n"$(
+				)" [Y]=Run Roaming/[N]=Exit\n" \
+				"$inputvar"
+			retval=$?
+			# Check return error
+			[ $retval -ne 0 ] && break
+			[ "$inputvar" = "Y" ] && {
+				clear
+				echo ; echo "[$aHostname]... Roaming New Frequency Now!!"
+				touch /tmp/.force_Ch_Roaming_$cStaIndex
 				sleep 1 # sleep 1 second
-				TestRoamingTimer=$((TestRoamingTimer+1))
-				[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
-			done
 
-			if [ -e /tmp/.force_Ch_Roaming_$cStaIndex ] ; then
-				rm -f /tmp/.force_Ch_Roaming_$cStaIndex
-				echo ; echo "[$aHostname]... Error! Roaming New Frequency!"
-			else
-				echo ; echo "[$aHostname]... Success! Roaming New Frequency."
-			fi
+				local TestRoamingTimer=0
+				local TestRoamingTimeout=30 # 30secs
+				while [ -e /tmp/.force_Ch_Roaming_$cStaIndex ] ; do
+					sleep 1 # sleep 1 second
+					TestRoamingTimer=$((TestRoamingTimer+1))
+					[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
+				done
 
-			sleep 1 # sleep 1 second
-		}
+				if [ -e /tmp/.force_Ch_Roaming_$cStaIndex ] ; then
+					rm -f /tmp/.force_Ch_Roaming_$cStaIndex
+					echo ; echo "[$aHostname]... Error! Roaming New Frequency!"
+				else
+					echo ; echo "[$aHostname]... Success! Roaming New Frequency."
+				fi
+
+				sleep 1 # sleep 1 second
+			}
+		fi
 		;;
 
 	X_ExitCancel | *)
diff --git a/files/DWSB/copy/etc/dwsb/dual_sta_roaming b/files/DWSB/copy/etc/dwsb/dual_sta_roaming
--- a/files/DWSB/copy/etc/dwsb/dual_sta_roaming
+++ b/files/DWSB/copy/etc/dwsb/dual_sta_roaming
@@ -228,38 +228,47 @@ while : ; do
 		;;
 
 	8_TestRoaming)
-		inputvar="N"
-		textinput \
-			"Dual-Station Roaming TEST... Now?? [Yes/No]\n\n"$(
-			)"Please Enter:\n"$(
-			)" [Y]=Run Roaming/[N]=Exit\n" \
-			"$inputvar"
-		retval=$?
-		# Check return error
-		[ $retval -ne 0 ] && break
-		[ "$inputvar" = "Y" ] && {
-			clear
-			echo ; echo "[$aHostname]... Roaming New Station Now!!"
-			touch /tmp/.force_Dual_Sta_Roaming
-			sleep 1 # sleep 1 second
-
-			local TestRoamingTimer=0
-			local TestRoamingTimeout=30 # 30secs
-			while [ -e /tmp/.force_Dual_Sta_Roaming ] ; do
+		local ACT_USE_DUALSTAROAM_MODE=$(grep "_USE_DUALSTAROAM_MODE" $CONFIG_org | sed 's/.*="\(.*\)"/\1/')
+		if [ "$ACT_USE_DUALSTAROAM_MODE" != "Y" ]; then
+			infobox \
+				 "\Z1ERROR!\n"$(
+				)"\Z0 Dual Station Roaming is not yet committed.\n"$(
+				)" Please try again after COMMIT it." \
+				5
+		else
+			inputvar="N"
+			textinput \
+				"Dual-Station Roaming TEST... Now?? [Yes/No]\n\n"$(
+				)"Please Enter:\n"$(
+				)" [Y]=Run Roaming/[N]=Exit\n" \
+				"$inputvar"
+			retval=$?
+			# Check return error
+			[ $retval -ne 0 ] && break
+			[ "$inputvar" = "Y" ] && {
+				clear
+				echo ; echo "[$aHostname]... Roaming New Station Now!!"
+				touch /tmp/.force_Dual_Sta_Roaming
 				sleep 1 # sleep 1 second
-				TestRoamingTimer=$((TestRoamingTimer+1))
-				[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
-			done
 
-			if [ -e /tmp/.force_Dual_Sta_Roaming ] ; then
-				rm -f /tmp/.force_Dual_Sta_Roaming
-				echo ; echo "[$aHostname]... Error! Roaming New Station!"
-			else
-				echo ; echo "[$aHostname]... Success! Roaming New Station."
-			fi
+				local TestRoamingTimer=0
+				local TestRoamingTimeout=30 # 30secs
+				while [ -e /tmp/.force_Dual_Sta_Roaming ] ; do
+					sleep 1 # sleep 1 second
+					TestRoamingTimer=$((TestRoamingTimer+1))
+					[ $TestRoamingTimer -ge $TestRoamingTimeout ] && break
+				done
 
-			sleep 1 # sleep 1 second
-		}
+				if [ -e /tmp/.force_Dual_Sta_Roaming ] ; then
+					rm -f /tmp/.force_Dual_Sta_Roaming
+					echo ; echo "[$aHostname]... Error! Roaming New Station!"
+				else
+					echo ; echo "[$aHostname]... Success! Roaming New Station."
+				fi
+
+				sleep 1 # sleep 1 second
+			}
+		fi
 		;;
 
 	X_ExitCancel | *)
diff --git a/files/DWSB/copy/etc/dwsb/link_int_checking b/files/DWSB/copy/etc/dwsb/link_int_checking
--- a/files/DWSB/copy/etc/dwsb/link_int_checking
+++ b/files/DWSB/copy/etc/dwsb/link_int_checking
@@ -192,26 +192,35 @@ while : ; do
 		;;
 
 	6_TestLnkErr)
-		inputvar="N"
-		textinput \
-			 "$cStaIndexStr AP Link Integriry error TEST... Now?? [Yes/No]\n\n"$(
-			)"Please Enter:\n"$(
-			)" [Y]=LinkError/[N]=Review\n" \
-			"N"
-		retval=$?
-		# Check return error
-		[ $retval -ne 0 ] && break
-		if [ "$inputvar" = "Y" ] ; then
-			clear
-			echo ; echo "[$aHostname]... Generate Link Integrity error for 10 seconds!"
+		local ACT_USE_LINKINTEGRITYCHECK_MODE=$(grep "_USE_LINKINTEGRITYCHECK_MODE" $CONFIG_org | sed 's/.*="\(.*\)"/\1/')
+		if [ "$ACT_USE_LINKINTEGRITYCHECK_MODE" != "Y" ]; then
+			infobox \
+				 "\Z1ERROR!\n"$(
+				)"\Z0 Link Integrity Checking is not yet committed.\n"$(
+				)" Please try again after COMMIT it." \
+				5
+		else
+			inputvar="N"
+			textinput \
+				 "$cStaIndexStr AP Link Integriry error TEST... Now?? [Yes/No]\n\n"$(
+				)"Please Enter:\n"$(
+				)" [Y]=LinkError/[N]=Review\n" \
+				"N"
+			retval=$?
+			# Check return error
+			[ $retval -ne 0 ] && break
+			if [ "$inputvar" = "Y" ]; then
+				clear
+				echo ; echo "[$aHostname]... Generate Link Integrity error for 10 seconds!"
 
-			touch /tmp/.force_LinkErr_$cStaIndex
-			sleep 10
-			rm -f /tmp/.force_LinkErr_$cStaIndex
+				touch /tmp/.force_LinkErr_$cStaIndex
+				sleep 10
+				rm -f /tmp/.force_LinkErr_$cStaIndex
 
-			echo ; echo "[$aHostname]... Finished Link Integrity error test."
+				echo ; echo "[$aHostname]... Finished Link Integrity error test."
 
-			sleep 3
+				sleep 3
+			fi
 		fi
 		;;
 
